package proyecto;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;                                  //Librerías a utilizar
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Anderson
 */
public class Interfaz extends javax.swing.JFrame {                    //Clase pública llamada Interfaz la cual es un JFrame
    
    FondoPanel fondo = new FondoPanel();                                //se crea el objeto llamado fondo
    
    public Interfaz() {                                                 //constructor
        this.setContentPane(fondo);                                     //Se pasa como parámetro el objeto llamado fondo 
        initComponents();
        setLocationRelativeTo(null);                                    //para que el Jframe salga en la parte central de la pantalla
        setResizable(false);                                            //para que no se pueda cambiar el tamaño de la interfaz
        limpiar();                                                      //Se llama al método para resetear los valores 
            
        Boton1.setBackground(Color.black);                              
        Boton2.setBackground(new Color(128,64,0));
        Boton3.setBackground(new Color(237,0,4));
        Boton4.setBackground(Color.orange);
        Boton5.setBackground(Color.yellow);
        Boton6.setBackground(new Color(0,143,57));                          //Para que los botones contengan un color establecido
        Boton7.setBackground(new Color(1,75,160));
        Boton8.setBackground(new Color(102,0,102));
        Boton9.setBackground(new Color(102,102,102));
        Boton10.setBackground(Color.white);
        
        Boton11.setBackground(Color.black);
        Boton12.setBackground(new Color(128,64,0));
        Boton13.setBackground(new Color(237,0,4));
        Boton14.setBackground(Color.orange);
        Boton15.setBackground(Color.yellow);
        Boton16.setBackground(new Color(0,143,57));                           //Para que los botones contengan un color establecido
        Boton17.setBackground(new Color(1,75,160));
        Boton18.setBackground(new Color(102,0,102));
        Boton19.setBackground(new Color(102,102,102));
        Boton20.setBackground(Color.white);
        
        Boton21.setBackground(Color.black);
        Boton22.setBackground(new Color(128,64,0));
        Boton23.setBackground(new Color(237,0,4));
        Boton24.setBackground(Color.orange);
        Boton25.setBackground(Color.yellow);
        Boton26.setBackground(new Color(0,143,57));
        Boton27.setBackground(new Color(1,75,160));                            //Para que los botones contengan un color establecido
        Boton28.setBackground(new Color(102,0,102));
        Boton29.setBackground(new Color(102,102,102));
        Boton30.setBackground(Color.white);
        Boton31.setBackground(new Color(212, 175, 55));
        Boton32.setBackground(new Color(192,192,192));
        
        Boton33.setBackground(new Color(128,64,0));
        Boton34.setBackground(new Color(237,0,4));                              //Para que los botones contengan un color establecido
        Boton35.setBackground(new Color(212, 175, 55));
        Boton36.setBackground(new Color(192,192,192));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Color9 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        Resultado1 = new javax.swing.JTextField();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Color1 = new javax.swing.JLabel();
        Color2 = new javax.swing.JLabel();
        Color3 = new javax.swing.JLabel();
        Color4 = new javax.swing.JLabel();
        Color5 = new javax.swing.JLabel();
        Color6 = new javax.swing.JLabel();
        Color7 = new javax.swing.JLabel();
        Color8 = new javax.swing.JLabel();
        Color10 = new javax.swing.JLabel();
        Boton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Color11 = new javax.swing.JLabel();
        Color12 = new javax.swing.JLabel();
        Color13 = new javax.swing.JLabel();
        Color14 = new javax.swing.JLabel();
        Color15 = new javax.swing.JLabel();
        Color16 = new javax.swing.JLabel();
        Color17 = new javax.swing.JLabel();
        Color18 = new javax.swing.JLabel();
        Color19 = new javax.swing.JLabel();
        Color20 = new javax.swing.JLabel();
        Boton11 = new javax.swing.JButton();
        Boton12 = new javax.swing.JButton();
        Boton13 = new javax.swing.JButton();
        Boton14 = new javax.swing.JButton();
        Boton15 = new javax.swing.JButton();
        Boton16 = new javax.swing.JButton();
        Boton17 = new javax.swing.JButton();
        Boton18 = new javax.swing.JButton();
        Boton19 = new javax.swing.JButton();
        Boton20 = new javax.swing.JButton();
        Resultado2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Color21 = new javax.swing.JLabel();
        Boton21 = new javax.swing.JButton();
        Color22 = new javax.swing.JLabel();
        Boton22 = new javax.swing.JButton();
        Color23 = new javax.swing.JLabel();
        Boton23 = new javax.swing.JButton();
        Color24 = new javax.swing.JLabel();
        Boton24 = new javax.swing.JButton();
        Color25 = new javax.swing.JLabel();
        Boton25 = new javax.swing.JButton();
        Color26 = new javax.swing.JLabel();
        Boton26 = new javax.swing.JButton();
        Color27 = new javax.swing.JLabel();
        Boton27 = new javax.swing.JButton();
        Color28 = new javax.swing.JLabel();
        Boton28 = new javax.swing.JButton();
        Color29 = new javax.swing.JLabel();
        Boton29 = new javax.swing.JButton();
        Color30 = new javax.swing.JLabel();
        Boton30 = new javax.swing.JButton();
        Boton31 = new javax.swing.JButton();
        Boton32 = new javax.swing.JButton();
        Color31 = new javax.swing.JLabel();
        Color32 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Resultado3 = new javax.swing.JTextField();
        Color33 = new javax.swing.JLabel();
        Color34 = new javax.swing.JLabel();
        Color35 = new javax.swing.JLabel();
        Color36 = new javax.swing.JLabel();
        Color37 = new javax.swing.JLabel();
        Boton33 = new javax.swing.JButton();
        Boton34 = new javax.swing.JButton();
        Boton35 = new javax.swing.JButton();
        Boton36 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Resultado4 = new javax.swing.JTextField();
        Boton37 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jbandas = new javax.swing.JComboBox<>();
        J1 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Kilo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Respuesta = new javax.swing.JTextArea();
        Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Poppins Light", 1, 36)); // NOI18N
        Titulo.setText("CALCULADORA DE OHM");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 440, 56));

        Color9.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color9.setText("Gris");
        jPanel1.add(Color9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 60, 40));

        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 50, 20));

        Resultado1.setEditable(false);
        Resultado1.setBackground(new java.awt.Color(238, 238, 238));
        Resultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resultado1ActionPerformed(evt);
            }
        });
        Resultado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Resultado1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Resultado1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Resultado1KeyTyped(evt);
            }
        });
        jPanel1.add(Resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 80, 20));

        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 50, 20));

        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 50, 20));

        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 50, 20));

        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 50, 20));

        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 50, 20));

        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 50, 20));

        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 50, 20));

        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 50, 20));

        Color1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color1.setText("Negro");
        jPanel1.add(Color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 60, 40));

        Color2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color2.setText("Marrón");
        jPanel1.add(Color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, 40));

        Color3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color3.setText("Rojo");
        jPanel1.add(Color3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 60, 40));

        Color4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color4.setText("Naranja");
        jPanel1.add(Color4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 40));

        Color5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color5.setText("Amarillo");
        jPanel1.add(Color5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 60, 40));

        Color6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color6.setText("Verde");
        jPanel1.add(Color6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, 40));

        Color7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color7.setText("Azul");
        jPanel1.add(Color7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 60, 40));

        Color8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color8.setText("Violeta");
        jPanel1.add(Color8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 60, 40));

        Color10.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color10.setText("Blanco");
        jPanel1.add(Color10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 60, 40));

        Boton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton10ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 50, 20));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel1.setText("Valor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 60, 30));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        jLabel3.setText("BANDA 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, 20));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        jLabel4.setText("TOLERANCIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 110, 20));

        Color11.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color11.setText("Negro");
        jPanel1.add(Color11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 40));

        Color12.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color12.setText("Marrón");
        jPanel1.add(Color12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, 40));

        Color13.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color13.setText("Rojo");
        jPanel1.add(Color13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, 40));

        Color14.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color14.setText("Naranja");
        jPanel1.add(Color14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 60, 40));

        Color15.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color15.setText("Amarillo");
        jPanel1.add(Color15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 60, 40));

        Color16.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color16.setText("Verde");
        jPanel1.add(Color16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 60, 40));

        Color17.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color17.setText("Azul");
        jPanel1.add(Color17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 60, 40));

        Color18.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color18.setText("Violeta");
        jPanel1.add(Color18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 60, 40));

        Color19.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color19.setText("Gris");
        jPanel1.add(Color19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 60, 40));

        Color20.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color20.setText("Blanco");
        jPanel1.add(Color20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 60, 40));

        Boton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton11ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 50, 20));

        Boton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton12ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 50, 20));

        Boton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton13ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 50, 20));

        Boton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton14ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 50, 20));

        Boton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton15ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 50, 20));

        Boton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton16ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 50, 20));

        Boton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton17ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 50, 20));

        Boton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton18ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 50, 20));

        Boton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton19ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 50, 20));

        Boton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton20ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 50, 20));

        Resultado2.setEditable(false);
        Resultado2.setBackground(new java.awt.Color(238, 238, 238));
        Resultado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resultado2ActionPerformed(evt);
            }
        });
        Resultado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Resultado2KeyTyped(evt);
            }
        });
        jPanel1.add(Resultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 80, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel5.setText("Valor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 60, 30));

        jLabel6.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        jLabel6.setText("BANDA 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, 20));

        jLabel7.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        jLabel7.setText("MULTIPLICADOR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 150, 20));

        Color21.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color21.setText("Negro");
        jPanel1.add(Color21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 60, 40));

        Boton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton21ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 50, 20));

        Color22.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color22.setText("Marrón");
        jPanel1.add(Color22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 60, 40));

        Boton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton22ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 50, 20));

        Color23.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color23.setText("Rojo");
        jPanel1.add(Color23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 60, 40));

        Boton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton23ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 50, 20));

        Color24.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color24.setText("Naranja");
        jPanel1.add(Color24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 60, 40));

        Boton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton24ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 50, 20));

        Color25.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color25.setText("Amarillo");
        jPanel1.add(Color25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 60, 40));

        Boton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton25ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 50, 20));

        Color26.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color26.setText("Verde");
        jPanel1.add(Color26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 60, 40));

        Boton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton26ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 50, 20));

        Color27.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color27.setText("Azul");
        jPanel1.add(Color27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 60, 40));

        Boton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton27ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 50, 20));

        Color28.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color28.setText("Violeta");
        jPanel1.add(Color28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 60, 40));

        Boton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton28ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 50, 20));

        Color29.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color29.setText("Gris");
        jPanel1.add(Color29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 60, 40));

        Boton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton29ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 50, 20));

        Color30.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color30.setText("Blanco");
        jPanel1.add(Color30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 60, 40));

        Boton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton30ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 50, 20));

        Boton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton31ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 50, 20));

        Boton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton32ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 50, 20));

        Color31.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color31.setText("Plateado");
        jPanel1.add(Color31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 60, 40));

        Color32.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color32.setText("Dorado");
        jPanel1.add(Color32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 60, 40));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setText("Valor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 60, 30));

        Resultado3.setEditable(false);
        Resultado3.setBackground(new java.awt.Color(238, 238, 238));
        Resultado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Resultado3KeyTyped(evt);
            }
        });
        jPanel1.add(Resultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 80, 20));

        Color33.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color33.setText("Marrón");
        jPanel1.add(Color33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 60, 40));

        Color34.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color34.setText("Rojo");
        jPanel1.add(Color34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 60, 40));

        Color35.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color35.setText("Dorado");
        jPanel1.add(Color35, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 60, 40));

        Color36.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color36.setText("Sin Banda");
        jPanel1.add(Color36, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 70, 40));

        Color37.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Color37.setText("Plateado");
        jPanel1.add(Color37, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 60, 40));

        Boton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton33ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 50, 20));

        Boton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton34ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 50, 20));

        Boton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton35ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 50, 20));

        Boton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton36ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 50, 20));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel9.setText("Valor");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 60, 40));

        Resultado4.setEditable(false);
        Resultado4.setBackground(new java.awt.Color(238, 238, 238));
        Resultado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resultado4ActionPerformed(evt);
            }
        });
        Resultado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Resultado4KeyTyped(evt);
            }
        });
        jPanel1.add(Resultado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 80, 20));

        Boton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton37ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 0, 760, 680));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Resistor.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 420, 130));

        Jbandas.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        Jbandas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nº. BANDAS", "4 BANDAS", "5 BANDAS" }));
        Jbandas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jbandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbandasActionPerformed(evt);
            }
        });
        getContentPane().add(Jbandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 170, -1));

        J1.setEditable(false);
        J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1ActionPerformed(evt);
            }
        });
        getContentPane().add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 20, 100));

        J2.setEditable(false);
        getContentPane().add(J2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 20, 100));

        J3.setEditable(false);
        getContentPane().add(J3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 20, 100));

        J4.setEditable(false);
        getContentPane().add(J4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 10, 100));

        Calcular.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculadora(2).png"))); // NOI18N
        Calcular.setText("Calcular");
        Calcular.setBorderPainted(false);
        Calcular.setContentAreaFilled(false);
        Calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calcular.setFocusPainted(false);
        Calcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Calcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculadora.png"))); // NOI18N
        Calcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculadora(1).png"))); // NOI18N
        Calcular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculadora.png"))); // NOI18N
        Calcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 100));

        Kilo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Kilo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letra-k.png"))); // NOI18N
        Kilo.setText("Kiloohmios\n");
        Kilo.setBorderPainted(false);
        Kilo.setContentAreaFilled(false);
        Kilo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kilo.setFocusPainted(false);
        Kilo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kilo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letra-k(2).png"))); // NOI18N
        Kilo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letra-k(1).png"))); // NOI18N
        Kilo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Kilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiloActionPerformed(evt);
            }
        });
        getContentPane().add(Kilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 120, 90));

        Respuesta.setEditable(false);
        Respuesta.setColumns(20);
        Respuesta.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        Respuesta.setRows(5);
        Respuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RespuestaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Respuesta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 280, 120));

        Borrar.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar(1).png"))); // NOI18N
        Borrar.setText("LIMPIAR");
        Borrar.setBorderPainted(false);
        Borrar.setContentAreaFilled(false);
        Borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Borrar.setFocusPainted(false);
        Borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Borrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"))); // NOI18N
        Borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar(3).png"))); // NOI18N
        Borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1ActionPerformed
        
    }//GEN-LAST:event_J1ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        J1.setBackground(Color.black);                                      //Se envía el color correspondiente a los Jtextfield de la imagen de la resistencia                                   
        int r=0;                                                            //se le asigna un valor a cada botón
        String res;                                                         //se inicializa una variable de tipo String
        res=Integer.toString(r);                                            // el valor se convierte de la variable r se convierte a String para mostrarlo en el Jtextfield de "valor"
        
        Resultado1.setText(res);                                            //se envía el valor de la resistencia al Jtextfield
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        J1.setBackground(new Color(128,64,0));                              //Se envía el color correspondiente a los Jtextfield de la imagen de la resistencia 
        int r=1;                                                            //se le asigna un valor a cada botón
        String res;                                                         //se inicializa una variable de tipo String
        res=Integer.toString(r);                                            // el valor se convierte de la variable r se convierte a String para mostrarlo en el Jtextfield de "valor"
        
        Resultado1.setText(res);                                            //se envía el valor de la resistencia al Jtextfield
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        J1.setBackground(new Color(237,0,4));                               //Se envía el color correspondiente a los Jtextfield de la imagen de la resistencia 
        int r=2;                                                            //se le asigna un valor a cada botón
        String res;                                                         //se inicializa una variable de tipo String
        res=Integer.toString(r);                                            // el valor se convierte de la variable r se convierte a String para mostrarlo en el Jtextfield de "valor"
        
        Resultado1.setText(res);                                            //se envía el valor de la resistencia al Jtextfield
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        J1.setBackground(Color.orange);
        int r=3;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
       J1.setBackground(Color.yellow);
        int r=4;
        String res;                                                        //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r         
        res=Integer.toString(r);
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        J1.setBackground(new Color(0,143,57));
        int r=5;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        J1.setBackground(new Color(1,75,160));
        int r=6;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        J1.setBackground(new Color(102,0,102));
        int r=7;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        J1.setBackground(new Color(102,102,102));
        int r=8;
        String res;
        res=Integer.toString(r);                                            //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton10ActionPerformed
        J1.setBackground(Color.white);
        int r=9;
        String res;                                                     //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado1.setText(res);
    }//GEN-LAST:event_Boton10ActionPerformed

    private void JbandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbandasActionPerformed
        Interfaz n= new Interfaz();                                     //se crea un objeto para cada interfaz  para usarlo en las opciones del combobox
         Interfaz_2 k = new Interfaz_2();                                //se crea un objeto para cada interfaz 
        if(Jbandas.getSelectedIndex()==1){                               //si la selección del usuario es en la posición 1 del combobox, teniendo en cuenta que la posicion 0 no está utilizandose
            n.setVisible(true);                                          //se muestra en pantalla el formulario de 4 bandas       
            dispose();                                                      //método para que se cierre el formulario que estaba abierto anteriormente a la elección
            
        }
        else if(Jbandas.getSelectedIndex()==2){                          //de lo contrario si se selecciona la segunda opción
            k.setVisible(true);                                             //aparecerá el formulario de las 5 bandas
            dispose();                                                   //método para que se cierre el formulario que estaba abierto anteriormente a la elección   
            
        }        
    }//GEN-LAST:event_JbandasActionPerformed

    private void Boton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton12ActionPerformed
        J2.setBackground(new Color(128,64,0));
        int r=1;
        String res;
        res=Integer.toString(r);                                            //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
            
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton12ActionPerformed

    private void Boton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton13ActionPerformed
       J2.setBackground(new Color(237,0,4));
        int r=2;
        String res;
        res=Integer.toString(r);                                            //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton13ActionPerformed

    private void Boton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton14ActionPerformed
        J2.setBackground(Color.orange);
        int r=3;                                                            //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        String res;
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton14ActionPerformed

    private void Boton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton15ActionPerformed
        J2.setBackground(Color.yellow);
        int r=4;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton15ActionPerformed

    private void Boton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton16ActionPerformed
        J2.setBackground(new Color(0,143,57));
        int r=5;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton16ActionPerformed

    private void Boton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton17ActionPerformed
        J2.setBackground(new Color(1,75,160));
        int r=6;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton17ActionPerformed

    private void Boton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton18ActionPerformed
        J2.setBackground(new Color(102,0,102));
        int r=7;
        String res;
        res=Integer.toString(r);                                                //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton18ActionPerformed

    private void Boton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton19ActionPerformed
        J2.setBackground(new Color(102,102,102));
        int r=8;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton19ActionPerformed

    private void Boton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton20ActionPerformed
        J2.setBackground(Color.white);
        int r=9;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton20ActionPerformed

    private void Boton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton11ActionPerformed
        J2.setBackground(Color.black);
        int r=0;                                                                //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        String res;
        res=Integer.toString(r);
        
        Resultado2.setText(res);
    }//GEN-LAST:event_Boton11ActionPerformed

    private void Boton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton21ActionPerformed
        J3.setBackground(Color.black);
        double r= 1;                                                            //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        String res;
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton21ActionPerformed

    private void Boton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton22ActionPerformed
        J3.setBackground(new Color(128,64,0));
        double r= 10;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton22ActionPerformed

    private void Boton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton23ActionPerformed
        J3.setBackground(new Color(237,0,4));
        double r= 100;
        String res;                                                                 //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton23ActionPerformed

    private void Boton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton24ActionPerformed
        J3.setBackground(Color.orange);
        double r= 1000;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        String res;
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton24ActionPerformed

    private void Boton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton25ActionPerformed
        J3.setBackground(Color.yellow);
        double r= 10000;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton25ActionPerformed

    private void Boton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton26ActionPerformed
        J3.setBackground(new Color(0,143,57));
        double r= 100000;
        String res;                                                                 //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton26ActionPerformed

    private void Boton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton27ActionPerformed
        J3.setBackground(new Color(1,75,160));
        double r= 1000000;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton27ActionPerformed

    private void Boton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton28ActionPerformed
        J3.setBackground(new Color(102,0,102));
        double r= 10000000;                                                 //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        String res;
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton28ActionPerformed

    private void Boton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton29ActionPerformed
        J3.setBackground(new Color(102,102,102));
        double r= 100000000;                                                    //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        String res;
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton29ActionPerformed

    private void Boton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton30ActionPerformed
        J3.setBackground(Color.white);
        double r= 1000000000;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton30ActionPerformed

    private void Boton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton31ActionPerformed
        J3.setBackground(new Color(212, 175, 55));
        double r= 0.1;
        String res;                                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton31ActionPerformed

    private void Boton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton32ActionPerformed
        J3.setBackground(new Color(192,192,192));
        double r= 0.01;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado3.setText(res);
    }//GEN-LAST:event_Boton32ActionPerformed

    private void Boton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton33ActionPerformed
        J4.setBackground(new Color(128,64,0));
        double r= 0.01;
        String res;                                                        //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r         
        res=Double.toString(r);
        Resultado4.setText(res);
    }//GEN-LAST:event_Boton33ActionPerformed

    private void Boton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton34ActionPerformed
        J4.setBackground(new Color(237,0,4));
        double r= 0.02;
        String res;
        res=Double.toString(r);                                             //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        Resultado4.setText(res);
    }//GEN-LAST:event_Boton34ActionPerformed

    private void Boton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton35ActionPerformed
        J4.setBackground(new Color(212, 175, 55));
        double r= 0.05;
        String res;                                                     //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado4.setText(res);
    }//GEN-LAST:event_Boton35ActionPerformed

    private void Boton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton36ActionPerformed
        J4.setBackground(new Color(192,192,192));
        double r= 0.1;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado4.setText(res);
    }//GEN-LAST:event_Boton36ActionPerformed

    private void Resultado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resultado4ActionPerformed
        
    }//GEN-LAST:event_Resultado4ActionPerformed

    private void Boton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton37ActionPerformed
        J4.setBackground(null);
        double r= 0.2;
        String res;                                                         //...Se realizan los mismos procedimientos con cada botón, solo se cambia su color y el valor de r
        res=Double.toString(r);
        Resultado4.setText(res);
    }//GEN-LAST:event_Boton37ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        if(Resultado1.getText().length()==0&&Resultado2.getText().length()==0&&Resultado3.getText().length()==0&&Resultado4.getText().length()==0){  //si ninguna opción fue elegida lanzará una alerta 
            JOptionPane.showMessageDialog(this, "INGRESE LOS DATOS CORRESPONDIENTES", "¡Error!", JOptionPane.ERROR_MESSAGE);        //para avisar que hace falta que seleccione valores
        }
        else if(Resultado1.getText().length()==0){                                                              //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN COLOR PARA LA BANDA 1", "¡Error!", JOptionPane.ERROR_MESSAGE); //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        else if(Resultado2.getText().length()==0){                                                                          //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN COLOR PARA LA BANDA 2", "¡Error!", JOptionPane.ERROR_MESSAGE);    //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        
        else if(Resultado3.getText().length()==0){                                                                          //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN VALOR PARA EL MULTIPLICADOR", "¡Error!", JOptionPane.ERROR_MESSAGE);  //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        else if(Resultado4.getText().length()==0){                                                                          //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN VALOR PARA LA TOLERANCIA", "¡Error!", JOptionPane.ERROR_MESSAGE); //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
                
        else{                                                                           //de lo contrario, si todas las opciones fueron seleccionadas se continúa con aplicar los cálculos necesarios
        int campo1=Integer.parseInt(Resultado1.getText());                                  //se crea una variable de tipo entero el cual recoge el valor ingresado por el usuario 
        int campo2=Integer.parseInt(Resultado2.getText());                                  //se crea una variable de tipo entero el cual recoge el valor ingresado por el usuario   
        double campo4=Double.parseDouble(Resultado3.getText());                         //se crea una variable de tipo double el cual recoge el valor ingresado por el usuario 
        double campo5=Double.parseDouble(Resultado4.getText());                         //se crea una variable de tipo double el cual recoge el valor ingresado por el usuario 
        
        String campoo1=Integer.toString(campo1);                                        
        String campoo2=Integer.toString(campo2);
        String campoo4=Double.toString(campo4);
        String campoo5=Double.toString(campo5);
        String conca=campoo1.concat(campoo2);                                           //Se concatenan los resultados para seguir la fórmula del cálculo de ohm, eso se guarda en la variable conca
        int result2= Integer.parseInt(conca);                                           //Se crea una variable de tipo entero para volver un valor numérico a la variable conca el cuál era String
        double resolv= result2*campo4;                                                  //Se multiplica con el valor del campo4 el cual es el valor del multiplicador y se guarda en la variable resolv de tipo double
        double resolv2= resolv*campo5;                                                  //se realiza el mismo paso solo que ahora se guarda en la variable resolv2 de tipo double
        String nuevo=Double.toString(resolv);                                           //se pasan a String para ser mostrados 
        String nuevo1=Double.toString(resolv2);                                         //se pasan a String para ser mostrados 
        
        
            if(Respuesta.getText().length()==0){                                        //Para que la respuesta salga una sola vez al ser presionado el botón
                Respuesta.append("EL VALOR DE LA RESISTENCIA ES:");
                Respuesta.append(System.getProperty("line.separator"));                     //para dar un salto de línea
                Respuesta.append(nuevo+"  +/-  "+ nuevo1 +"‎Ω");                         //se imprime el resultado en el Jtextarea correspondiente
            }
            else{                                                                       //de lo contrario si el usuario sigue presionando el botón de calcular no se mostrarán más veces el mismo resultado
                
            }
        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void KiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiloActionPerformed
        if(Resultado1.getText().length()==0&&Resultado2.getText().length()==0&&Resultado3.getText().length()==0&&Resultado4.getText().length()==0){ //si ninguna opción fue elegida lanzará una alerta
            JOptionPane.showMessageDialog(this, "INGRESE LOS DATOS CORRESPONDIENTES", "¡Error!", JOptionPane.ERROR_MESSAGE);                            //para avisar que hace falta que seleccione valores
        }
        else if(Resultado1.getText().length()==0){                                                                          //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN COLOR PARA LA BANDA 1", "¡Error!", JOptionPane.ERROR_MESSAGE);    //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        else if(Resultado2.getText().length()==0){                                                                          //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN COLOR PARA LA BANDA 2", "¡Error!", JOptionPane.ERROR_MESSAGE);    //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        
        else if(Resultado3.getText().length()==0){                                                                              //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN VALOR PARA EL MULTIPLICADOR", "¡Error!", JOptionPane.ERROR_MESSAGE);  //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        else if(Resultado4.getText().length()==0){                                                                              //en dado caso no haya elejido una opción
            JOptionPane.showMessageDialog(this, "ELIJA UN VALOR PARA LA TOLERANCIA", "¡Error!", JOptionPane.ERROR_MESSAGE); //lanzará una alerta y dirá cuál le hace falta seleccionar
        }
        
        else{                                                                               //de lo contrario, si todas las opciones fueron seleccionadas se continúa con aplicar los cálculos necesarios                                                   
        int campo1=Integer.parseInt(Resultado1.getText());                                  //se crea una variable de tipo entero el cual recoge el valor ingresado por el usuario 
        int campo2=Integer.parseInt(Resultado2.getText());                                  //se crea una variable de tipo entero el cual recoge el valor ingresado por el usuario 
        double campo4=Double.parseDouble(Resultado3.getText());                             //se crea una variable de tipo double el cual recoge el valor ingresado por el usuario
        double campo5=Double.parseDouble(Resultado4.getText());                             //se crea una variable de tipo double el cual recoge el valor ingresado por el usuario

        String campoo1=Integer.toString(campo1);
        String campoo2=Integer.toString(campo2);
        
        String campoo4=Double.toString(campo4);
        String campoo5=Double.toString(campo5);
        String conca=campoo1.concat(campoo2);                                               //Se concatenan los resultados para seguir la fórmula del cálculo de ohm, eso se guarda en la variable conca
        int result2= Integer.parseInt(conca);                                               //Se crea una variable de tipo entero para volver un valor numérico a la variable conca el cuál era String
        double resolv= result2*campo4;                                                      //Se multiplica con el valor del campo4 el cual es el valor del multiplicador y se guarda en la variable resolv de tipo double
        double resolv2= resolv*campo5;                                                      //se realiza el mismo paso solo que ahora se guarda en la variable resolv2 de tipo double
        double convertidor=resolv/1000;                                                     //Los resultados son divididos entre 1000 para mostrar la respuesta en kiloohmios
        double convertidor2=resolv2/1000;                                                   //Los resultados son divididos entre 1000 para mostrar la respuesta en kiloohmios
        JOptionPane.showMessageDialog(this, "LA RESPUESTA EN K‎Ω ES: "+convertidor+"  +/-  "+convertidor2+" K‎Ω ", "Kiloohmios", JOptionPane.INFORMATION_MESSAGE);  //Se muestra una ventana emergente con los resultados en kohm
        }
    }//GEN-LAST:event_KiloActionPerformed

    private void Resultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resultado1ActionPerformed
           
        
    }//GEN-LAST:event_Resultado1ActionPerformed

    private void Resultado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Resultado1KeyTyped
            
     
    }//GEN-LAST:event_Resultado1KeyTyped

    private void Resultado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resultado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resultado2ActionPerformed

    private void Resultado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Resultado2KeyTyped
         
    }//GEN-LAST:event_Resultado2KeyTyped

    private void Resultado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Resultado3KeyTyped
        
    }//GEN-LAST:event_Resultado3KeyTyped

    private void Resultado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Resultado4KeyTyped
         
    }//GEN-LAST:event_Resultado4KeyTyped

    private void RespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestaKeyTyped
        
    }//GEN-LAST:event_RespuestaKeyTyped

    private void Resultado1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Resultado1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resultado1KeyPressed

    private void Resultado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Resultado1KeyReleased
        
    }//GEN-LAST:event_Resultado1KeyReleased

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        limpiar();
    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton10;
    private javax.swing.JButton Boton11;
    private javax.swing.JButton Boton12;
    private javax.swing.JButton Boton13;
    private javax.swing.JButton Boton14;
    private javax.swing.JButton Boton15;
    private javax.swing.JButton Boton16;
    private javax.swing.JButton Boton17;
    private javax.swing.JButton Boton18;
    private javax.swing.JButton Boton19;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton20;
    private javax.swing.JButton Boton21;
    private javax.swing.JButton Boton22;
    private javax.swing.JButton Boton23;
    private javax.swing.JButton Boton24;
    private javax.swing.JButton Boton25;
    private javax.swing.JButton Boton26;
    private javax.swing.JButton Boton27;
    private javax.swing.JButton Boton28;
    private javax.swing.JButton Boton29;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton30;
    private javax.swing.JButton Boton31;
    private javax.swing.JButton Boton32;
    private javax.swing.JButton Boton33;
    private javax.swing.JButton Boton34;
    private javax.swing.JButton Boton35;
    private javax.swing.JButton Boton36;
    private javax.swing.JButton Boton37;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel Color1;
    private javax.swing.JLabel Color10;
    private javax.swing.JLabel Color11;
    private javax.swing.JLabel Color12;
    private javax.swing.JLabel Color13;
    private javax.swing.JLabel Color14;
    private javax.swing.JLabel Color15;
    private javax.swing.JLabel Color16;
    private javax.swing.JLabel Color17;
    private javax.swing.JLabel Color18;
    private javax.swing.JLabel Color19;
    private javax.swing.JLabel Color2;
    private javax.swing.JLabel Color20;
    private javax.swing.JLabel Color21;
    private javax.swing.JLabel Color22;
    private javax.swing.JLabel Color23;
    private javax.swing.JLabel Color24;
    private javax.swing.JLabel Color25;
    private javax.swing.JLabel Color26;
    private javax.swing.JLabel Color27;
    private javax.swing.JLabel Color28;
    private javax.swing.JLabel Color29;
    private javax.swing.JLabel Color3;
    private javax.swing.JLabel Color30;
    private javax.swing.JLabel Color31;
    private javax.swing.JLabel Color32;
    private javax.swing.JLabel Color33;
    private javax.swing.JLabel Color34;
    private javax.swing.JLabel Color35;
    private javax.swing.JLabel Color36;
    private javax.swing.JLabel Color37;
    private javax.swing.JLabel Color4;
    private javax.swing.JLabel Color5;
    private javax.swing.JLabel Color6;
    private javax.swing.JLabel Color7;
    private javax.swing.JLabel Color8;
    private javax.swing.JLabel Color9;
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JComboBox<String> Jbandas;
    private javax.swing.JButton Kilo;
    private javax.swing.JTextArea Respuesta;
    private javax.swing.JTextField Resultado1;
    private javax.swing.JTextField Resultado2;
    private javax.swing.JTextField Resultado3;
    private javax.swing.JTextField Resultado4;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    class FondoPanel extends JPanel                 //clase interna llamada fondo panel extendida de la Clase JPanel
    {
        private Image imagen;                       //variable privada de tipo Image llamada imagen
        
        @Override                                   //para anular un método de una superclase, Se utiliza para asegurar que un método de superclase esté anulado y no simplemente sobrecargado.
        public void paint(Graphics g)               //Método paint que tiene como parámetro Graphics g
        {
            imagen = new ImageIcon(getClass().getResource("/img/fondoprueba2.jpg")).getImage(); //se crea un objeto y se utiliza el método getResource para localizar la imagen
            
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);    //para dibujar la imagen y también cambiar su tamaño. getWidth para tener el ancho del panel y getHeight para tener la altura del panel.
            
            setOpaque(false);          //Establece la transparencia del fondo de un texto estampado
            
            super.paint(g);
        }
    }
    
    private void limpiar(){                                     //Método para limpiar y volver a ingresar valores
        Resultado1.setText("");                                 
        Resultado2.setText("");
        Resultado3.setText("");                                 //Los resultados de los Jtextfield en la parte de "valor" se reinician
        Resultado4.setText("");
        Respuesta.setText("");
        
        J1.setBackground(Color.white);
        J2.setBackground(Color.white);                          //Los Jtextfield que se encuentran en la imagen de la resistencia se colocan en color blanco
        J3.setBackground(Color.white);
        J4.setBackground(Color.white);
        
        
    }
    
  
}

